Repository guardiac/battleship, pull requests merged in 2020-07, with the labels that each got.

#52 I3/turn/display boards
  lib/board.rb
  lib/turn.rb
  test/turn_test.rb
Labels: new feature

#57 I3/turn/computer shot
  lib/board.rb
  lib/turn.rb
  test/board_test.rb
Labels: new feature

#59 Turn/human shot
  lib/board.rb
  lib/turn.rb
  test/board_test.rb
  test/turn_test.rb
Labels: new feature

#64 I3/turn/results
  lib/cell.rb
  lib/turn.rb
Labels: new feature

#65 Remove parentheses from cell tests
  test/cell_test.rb
Labels: enhancement

#69 Board/valid coords
  lib/board.rb
  lib/cell.rb
  test/board_test.rb
  test/cell_test.rb
Labels: enhancement

#71 Fix get user input recursive return bug
  lib/game.rb
Labels: bug

#76 Add 'true' flag to human player board render in display_boards method
  lib/turn.rb
Labels: bug

#77 I4/ai/crossguess
  lib/board.rb
  lib/turn.rb
  test/board_test.rb
Labels: new feature

#74 I3/board/reset bug
  battleship_runner.rb
  lib/game.rb
  test/game_test.rb
Labels: bug

#70 Dynamic sizing
  lib/board.rb
  lib/game.rb
Labels: enhancement, new feature

#66 Cell/render
  lib/turn.rb
  test/cell_test.rb
Labels: enhancement

#78 Add custom board height and width message methods to game
  lib/game.rb
Labels: enhancement

#82 Rake
  Rakefile.rb
  test/cell_test.rb
  test/game_test.rb
Labels: enhancement

#80 Messages
  lib/game.rb
  lib/messages.rb
  lib/turn.rb
  test/game_test.rb
  test/messages_test.rb
  test/turn_test.rb
Labels: enhancement

#89 Puts thanks
  lib/game.rb
Labels: bug

#87 Add yes no prompt until method to game
  lib/game.rb
Labels: bug

#94 Repeat hit warning
  lib/messages.rb
  lib/turn.rb
  test/messages_test.rb
Labels: bug
